name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Icons
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
        if: ${{ success() || failure() }}

      - name: >-
          🌸 Anilist watch list and reading list - Favorites anime and currently
          watching
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
          output_action: none
          delay: 120
          user: yuk1uno
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🌸 Anilist watch list and reading list - Favorites characters
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          output_action: none
          delay: 120
          user: yuk1uno
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
